spring.application.name=rest_api
spring.h2.console.enabled=true

# Ensure the database is persisted or named so you can find it
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=